name: Success deployment status notifier
on:
  deployment_status:
jobs:
  build:
    name: Build
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Sending message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>âœ…ï¸ Deployment succeeded!</b>

            <b>ğŸ”ï¸ Feel free to check: <a href="https://samith.info">samith.info</a></b>

            - repo: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            - changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
