name: Success deployment status notifier
on:
  deployment_status:
jobs:
  build:
    name: Build
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Sending message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <b>âœ…ï¸ The website is successfully deployed!</b>

            ğŸ”ï¸ Feel free to check the website: <a href="https://samith.info"><b>samith.info</b></a>

            - Repository: <a href="https://github.com/${{ github.repository }}">${{ github.repository }}</a>
            - See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
